// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpcjcjidcwloqxmfflsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwY2pjamlkY3dsb3F4bWZmbHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzcxNTAsImV4cCI6MjA2OTU1MzE1MH0.hC5SBNoWY-gr7raJqmbOld4vmdoI1J79EPz9DNI1J4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});